export const START_FETCH_NEWS = 'START_FETCH_NEWS';
export const SUCCESS_FETCH_NEWS = 'SET_DATA_NEWS';
export const FAILURE_RESPONSE_NEWS = 'FAILURE_RESPONSE';
export const FILTER_DATA_NEWS = 'FILTER_DATA_NEWS';
export const SELECTED_CATEGORY = 'SELECTED_CATEGORY';
export const SET_CATEGORY = 'SET_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const START_NEWS_SAGA = 'START_NEWS_SAGA';
